[build]
builder = "DOCKERFILE"
timeout = 1800  # 30 minutes
retries = 3

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2
replicas = 1

[[services]]
name = "gary-zero"

[services.source]
repo = "GaryOcean428/gary-zero"
branch = "main"

[services.variables]
WEB_UI_HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
RAILPACK_PRUNE_DEPS = "false"
NIXPACKS_PYTHON_VERSION = "3.11"