[build]
builder = "railpack"
timeout = 1800  # 30 minutes
retries = 3

[deploy]
startCommand = "python start_uvicorn.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
replicas = 1

# Volume configuration for persistent data storage
[[volumes]]
name = "gary-zero-data"
mountPath = "/app/data"
size = 10

[[services]]
name = "gary-zero"

[services.source]
repo = "GaryOcean428/gary-zero"
branch = "main"

[services.variables]
WEB_UI_HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
RAILPACK_PYTHON_VERSION = "3.13"
RAILPACK_PACKAGE_MANAGER = "uv"

# FastAPI Configuration
API_DOCS_ENABLED = "false"  # Disable docs in production
CORS_ORIGINS = "*"

# SearXNG Railway service URL (will be set by Railway)
SEARXNG_URL = "http://${{searchxng.RAILWAY_PRIVATE_DOMAIN}}:${{searchxng.PORT}}"

# Kali Shell Service Configuration (Railway inter-service communication)
KALI_SHELL_URL = "http://${{kali-linux-docker.RAILWAY_PRIVATE_DOMAIN}}:${{kali-linux-docker.PORT}}"
KALI_SHELL_HOST = "${{kali-linux-docker.RAILWAY_PRIVATE_DOMAIN}}"
KALI_SHELL_PORT = "${{kali-linux-docker.PORT}}"
KALI_USERNAME = "${{kali-linux-docker.USERNAME}}"
KALI_PASSWORD = "${{kali-linux-docker.PASSWORD}}"
KALI_PUBLIC_URL = "https://${{kali-linux-docker.RAILWAY_PUBLIC_DOMAIN}}"

# E2B Configuration (secure cloud sandbox execution)
E2B_API_KEY = "${{E2B_API_KEY}}"

# Data directory for persistent storage
DATA_DIR = "/app/data"

# Code execution configuration for Railway deployment
CODE_EXECUTION_MODE = "secure"
DISABLE_SSH_EXECUTION = "true"
USE_E2B_EXECUTION = "true"

# Search provider configuration
SEARCH_PROVIDER = "searxng"

# Logging configuration
LOG_LEVEL = "INFO"
ENABLE_REQUEST_LOGGING = "false"