[build]
builder = "NIXPACKS"
timeout = 1800  # 30 minutes
retries = 3
buildCommand = "python -m pip install --upgrade pip uv && uv sync --locked"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:${PORT:-8000} --workers 1 --timeout 120 --preload wsgi:application"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
replicas = 1

[[services]]
name = "gary-zero"

[services.source]
repo = "GaryOcean428/gary-zero"
branch = "main"

[services.variables]
WEB_UI_HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
RAILPACK_PRUNE_DEPS = "false"
NIXPACKS_PYTHON_VERSION = "3.11"