[build]
builder = "NIXPACKS"
buildCommand = "npm install && pip install -r requirements.txt"

[deploy]
startCommand = "python run_ui.py --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "gary-zero"

[services.source]
repo = "GaryOcean428/gary-zero"
branch = "main"

[services.variables]
NODE_ENV = "production"
WEB_UI_PORT = { $ref = "PORT" }
WEB_UI_HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"