name: Dependency Validation

on:
  push:
    paths:
      - 'requirements.in'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'requirements.in'
      - 'requirements.txt'

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv
    
    - name: Regenerate requirements.txt
      run: |
        uv pip compile requirements.in -o requirements.check.txt
    
    - name: Compare requirements files
      run: |
        # Sort and normalize both files for comparison
        sort requirements.txt > requirements.sorted.txt
        sort requirements.check.txt > requirements.check.sorted.txt
        
        # Check if files differ
        if ! diff -q requirements.sorted.txt requirements.check.sorted.txt > /dev/null; then
          echo "❌ ERROR: requirements.txt is out of sync with requirements.in!"
          echo "Please regenerate requirements.txt using:"
          echo "  uv pip compile requirements.in -o requirements.txt"
          exit 1
        else
          echo "✅ requirements.txt is in sync with requirements.in"
        fi
    
    - name: Verify critical dependencies
      run: |
        # Check for FastAPI and related packages
        for pkg in fastapi uvicorn websockets; do
          if ! grep -q "^$pkg" requirements.txt; then
            echo "❌ ERROR: Missing critical dependency: $pkg"
            exit 1
          fi
        done
        echo "✅ All critical dependencies present"
